services:
  dynamodb-local:
    command: '-jar DynamoDBLocal.jar -dbPath ./data'
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-local
    ports:
      - '4000:4000'
    volumes:
      - './docker/dynamodb:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal

  web:
    build: .
    depends_on:
      - dynamodb-local
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - .:/usr/src/app/ts-graphql-dynamodb
      - /usr/src/app/ts-graphql-dynamodb/node_modules
    command: yarn dev
    environment:
      AWS_ACCESS_KEY_ID: AKIA5MODO24DYMRPT665
      AWS_SECRET_ACCESS_KEY: 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
      PORT: 5000
